stages:          # List of stages for jobs, and their order of execution
  - build-image
  - publish-image
  - deploy-app

build-image-job:       
  stage: build-image
  script:
    - cd counter-app
    - docker image prune -f	
    - docker build -t counter-app:$CI_COMMIT_SHORT_SHA .
    - docker images

push-image-job:   
  stage: publish-image
  script:
    - docker tag counter-app:$CI_COMMIT_SHORT_SHA $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA

deploy-app-job:      
  stage: deploy-app 
  environment: production
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$VM_IPADDRESS "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
    - ssh $SSH_USER@$VM_IPADDRESS "docker pull $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA"
    - ssh $SSH_USER@$VM_IPADDRESS "docker stop \$(docker ps -a -q)"
    - ssh $SSH_USER@$VM_IPADDRESS "docker rm \$(docker ps -a -q)"
    - ssh $SSH_USER@$VM_IPADDRESS "docker run -d -p 80:5000 $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA"
    
