stages:          # List of stages for jobs, and their order of execution
  - build-image
  - publish-image
  - deploy-app

build-image-job:       
  stage: build-image
  script:
    - cd counter-app
    - docker image prune -f	
    - docker build -t counter-app:$CI_COMMIT_SHORT_SHA .
    - docker images

push-image-job:   
  stage: publish-image
  script:
    - docker tag counter-app:$CI_COMMIT_SHORT_SHA $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA

deploy-app-job:      
  stage: deploy-app 
  environment: production
  script:
    - docker pull $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA
    - docker rm -f counter-app || true
    - docker run -d -p 80:80 --name counter-app $DOCKER_USERNAME/counter-app:$CI_COMMIT_SHORT_SHA
